''' Analizador de tramas '''

dic_trad={"LCANTEFECTPRODUCTOS":2,
            "LCANTTARJ":2,
            "LCLAVE":4,
            "LCODOP":4,
            "LCODPOST":5,
            "LCODRET":3,
            "LCOMPROBANTE":8,
            "LCONCEPTO":2,
            "LDESCSERV":-1,
            "LDIASDESC":3,
            "LDOC":15,
            "LDOM":50,
            "LESTADOOP":3,
            "LESTADO":2,
            "LFECHA":8,
            "LFLAG":1,
            "LHORA":6,
            "LLOC":25,
            "LMESSBIENVENIDA":80,
            "LCODIGOERROR":2,
            "LMESSFROMBRIS":80,
            "LMONEDA":2,
            "LMONTO":14,
            "LNACIONALIDAD":3,
            "LNOMBRESUC":50,
            "LNUMCAJ":5,
            "LNUMREF":8,
            "LOBSERVACIONES":254,
            "LOPERADORA":3,
            "LPARTEDEC":2,
            "LPARTEDEC4":4,
            "LPARTEDEC6":6,
            "LPLAZO":3,
            "LPRODUCTO":20,
            "LPROV":25,
            "LRAZONSOCIAL":50,
            "LRECLAMO":2,
            "LSESSIONID":8,
            "LSUCURSAL":3,
            "LTASA":5,
            "LTEL":16,
            "LTIPODOC":3,
            "LTIPOOP":2,
            "LTIPOPAGO":2,
            "LTIPOPRODUCTO":1,
            "LTIPOSERV":2,
            "LCBU":23,
            "LESEMPLEADO":2,
            "LCODIGOFONDO":2,
            "LTIPOFONDO":2,
            "LVALORCUOTAPARTE":12,
            "LPARTEDECIMALCUOTAPARTE":6,
            "LCANTIDADCUOTASPARTE":16,
            "LDESCRIPCIONFONDO":30,
            "LRENDIMIENTO":12,
            "LMONEDAFCI":20,
            "LCODMONEDAFCI":2,
            "LFECHAFCI":10,
            "LCODPOSTDE8":8,
            "LCATEGORIAUSUARIO":1,
            "LPRODUCTORESUMIDO":10,
            "LNROINVERSOR":13,
            "LDESCRIPCION":20,
            "LCODOPERACION":2,
            "LTITULO":50,
            "LINFORMACION":5000,
            "LBANCO":30,
            "LNODO":4,
            "LRAZSOCIAL":50,
            "LMOTIVO":30,
            "LTELEFONO":30,
            "LOBS":80,
            "LCATEGORIACIS":10,
            "LBLANCOS":10,
            "LCODIGOMONEDA":1,
            "LNCUOTAS":4,
            "LDIAS":3,
            "LTIPOPRESTAMO":3,
            "LTASAPRESTAMO":7,
            "LDESCPRESTAMO":30,
            "LREFER":22,
            "LENTE":5,
            "LSUBENTE":3,
            "LMESAÑO":6,
            "LCODIS":4,
            "LCOCAN":3,
            "LCOSIT":15,
            "LCOSITADI":10,
            "LOBSCRM":256,
            "LNOMBRE":35,
            "LSEGMENTO":50,
            "LOFICIAL":64,
            "LOFICIAL1":6,
            "LIR":5,
            "LCODCOM":4,
            "LDESCOM":30,
            "LCANTIDAD":3,
            "LCANT":3,
            "LCATDES":32,
            "LPRODES":30,
            "LDESEST":32,
            "LDESESTABR":8,
            "LDESIS":50,
            "LDESISABR":25,
            "LDESCRI":255,
            "LDESBEN":512,
            "LFECHASTR":10,
            "LIDCLIENTE":12,
            "LIDBANELCO":19,
            "LCTACTECR":10,
            "LCATEIVA":3,
            "LTIPOTTASA":1,
            "LPLAZOEXLO":4,
            "LCODCOMPANIA":3,
            "LMONEDAEXLO":1,
            "LTIO":3,
            "LAUX":3,
            "LIDULTMO":2,
            "LIP":15,
            "LARCHIVO":20,
            "LULTIMPRE":5,
            "LAGENT":5,
            "LPOSICION":4,
            "LSPLIT":4,
            "LTELEFFAX":13,
            "LCANTAVISOS":4,
            "LCODBCO":5,
            "LCUIT":11,
            "LPRODUCTOMAILTARJETA":20,
            "LMESSAGEFROMONLINE":80,
            "1":1,
            "2":2,
            "3":3,
            "4":4,
            "5":5,
            "6":6,
            "7":7,
            "8":8,
            "9":9}

dic_cod_ret={"OK":0,
            "Cliente identificado con clave OK":0,
            "On-line":0,
            "Off-line":1,
            "Saldo de cierre":2,
            "Cliente No identificado":2,
            "Cliente No identificado  Suspendida":12,
            "Cliente No identificado  Nocturna":14,
            "Banca Cerrada":3,
            "Operable Nocturna":4,
            "Clave actual errónea":5,
            "Clave Inválida":6,
            "Cliente identificado con clave NULL":7,
            "Clave No inicializada":7,
            "Documento Indeterminado":8,
            "Quedaría pendiente":9,
            "Quedó pendiente":10,
            "Quedó pendiente el crédito":11,
            "Solicitud Previa":15,
            "Criterio de búsqueda muy amplio (búsqueda del cliente por razón social)":19,
            "Banca suspendida":20,
            "Clave Bloqueada":21,
            "Reset de Clave":22,
            "Reset de la Segunda Clave":23,
            "Segunda Clave Bloqueada":24,
            "Clave actual errónea":25,
            "Segunda Clave Inválida":26,
            "Cliente identificado con segunda clave NULL":27,
            "Segunda clave No inicializada":27,
            "Cliente con problemas de Fraude":28,
            "C{iente con sesión abierta":29,
            "Cliente con alta en proceso":30,
            "Cliente con baja en proceso":31,
            "Cliente con alta rechazada":32,
            "Cliente con  novedad en proceso":33,
            "El cliente pertenece al programa":34,
            "Supera máximo permitido por Banca Telefónica":50,
            "La cuenta es de orden conjunta":51,
            "Cuenta Inexistente":52,
            "Documento no válido":53,
            "Difiere la moneda del plazo fijo con la moneda de la cuenta de débito":100,
            "Monto del plazo fijo inferior al mínimo permitido":101,
            "Plazo (días) inferior al mínimo permitido":102,
            "Operaciones de Fondos  No Permitidas (Banca de Fondos Cerrada)  ":104,
            "Importe a Rescatar mayor al Saldo del Fondo":105,
            "Operaciones de Fondos Habilitadas":106,
            "Operaciones de Fondos No Habilitadas":107,
            "Las cuentas de la transferencias son de distinta moneda":200,
            "Las cuentas de la compra-venta son de igual moneda":300,
            "Pizarra suspendida":301,
            "Pizarra cerrada":302,
            "Fecha del pago de tarjeta menor a la fecha actual":400,
            "Operación No Permitida":500,
            "Error ´bancario´en ONLINE":777,
            "Error en el procesamiento de la operación":888,
            "Last_Packet":999,
            "CODRET_INTERNETBANKING_OK":0,
            "CODRET_INTERNETBANKING_NO_REGISTRADO":1,
            "WRONG":888}

flags = ["LDOC","LTIPODOC",4,"LRAZONSOCIAL","LNACIONALIDAD","LFECHA","LDOM","LCODPOST","LLOC","LTEL","LDOM","LCODPOST","LLOC","LTEL","LSUCURSAL","LCANTEFECTPRODUCTOS","LTIPOPRODUCTO","LPRODUCTO","LFLAG",2,"LFLAG","LFLAG","3",8,"LCATEGORIACIS","LFLAG","LNODO","LFLAG","LFECHA","LFLAG","LFLAG","LFLAG","LFLAG","LFECHA","LFLAG","LFLAG","LCODBCO","LFLAG","LCUIT","LFLAG","30"]

def transformar_flag(FLAG):
    if type(FLAG) == type(4): return FLAG
    try:
        return dic_trad[FLAG]
    except:
        return int(FLAG)

def transformar_lista(Lista):
    Lista_mapeada = list(map(transformar_flag, Lista))
    return Lista_mapeada

def mostrar_info(Trama):
    spliteado = Trama.split(";")
    _id = spliteado[0]
    _dt = spliteado[1]
    _nOp = spliteado[2]

    pass

def dt_analyzer(DT):
    '''20180228_1120210320'''
    year = DT[0:4]
    month = DT[4:6]
    day = DT[6:8]
    hour = DT[9:11]
    minute = DT[11:13]
    second = DT[13:15]
    milisecond = DT[15:]

    return (year,month,day,hour,minute,second,milisecond)

def dt_format(args):
    y,m,d,H,M,S,Mm = args
    return("{0}/{1}/{2} - {3}:{4}:{5}:{6}".format(d,m,y,H,M,S,Mm))

dt = dt_analyzer("20180228_1120210320")
print(dt_format(dt))
